# Welcome to cwOpenDJ-Setup
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alan Miller
email: alan.miller3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  No description yet
baseurl: "/alanmiller" # the subpath of your site, e.g. /blog
url: "http://github.com" # the base hostname & protocol for your site
github_username:  alanmiller

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
